# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('keystone_auth_url', models.CharField(max_length=2083)),
                ('keystone_user', models.CharField(max_length=100)),
                ('keystone_password', models.CharField(max_length=250)),
                ('keystone_tenant_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clouds',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_dirty', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'endpoints',
            },
        ),
        migrations.CreateModel(
            name='ICMPTestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_tenant', models.CharField(max_length=500)),
                ('dest_tenant', models.CharField(max_length=500)),
                ('src_ep', models.TextField()),
                ('dest_ep', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('rtt_min', models.FloatField()),
                ('rtt_max', models.FloatField()),
                ('rtt_avg', models.FloatField()),
                ('packets_received', models.IntegerField()),
                ('packets_transmitted', models.IntegerField()),
                ('packet_loss_percent', models.FloatField()),
            ],
            options={
                'db_table': 'icmp_test_results',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(max_length=255)),
                ('network_name', models.CharField(max_length=255)),
                ('shared', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=25)),
                ('is_selected', models.BooleanField(default=False)),
                ('endpoint_count', models.IntegerField(default=True, null=True)),
                ('is_dirty', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_id', models.CharField(max_length=255)),
                ('subnet_name', models.CharField(max_length=255)),
                ('cidr', models.CharField(max_length=255)),
                ('allocation_pool_start', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_range_start', models.TextField(blank=True, max_length=15, null=True)),
                ('ip_range_end', models.TextField(blank=True, max_length=15, null=True)),
                ('allocation_pool_end', models.GenericIPAddressField(blank=True, null=True)),
                ('is_dirty', models.BooleanField(default=False)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='cloud.Network')),
            ],
            options={
                'db_table': 'subnets',
            },
        ),
        migrations.CreateModel(
            name='TCPTestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_tenant', models.CharField(max_length=500)),
                ('dest_tenant', models.CharField(max_length=500)),
                ('src_ep', models.TextField()),
                ('dest_ep', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('retr', models.IntegerField()),
                ('bandwidth', models.CharField(max_length=20)),
                ('interval_time', models.CharField(max_length=20)),
                ('transferred', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tcp_test_results',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('tenant_name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_dirty', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('allowed_delta_percentage', models.FloatField()),
                ('test_result_path', models.CharField(max_length=250)),
                ('number_of_workers', models.IntegerField()),
                ('remote_user', models.CharField(max_length=100)),
                ('remote_pass', models.CharField(max_length=100)),
                ('test_method', models.CharField(max_length=100)),
                ('iperf_duration', models.IntegerField()),
                ('test_type', models.CharField(choices=[('all', 'All'), ('intra-tenant', 'Intra Tenant'), ('inter-tenant', 'Inter Tenant'), ('south-north', 'South to North'), ('north-south', 'North to South')], default='all', max_length=20)),
                ('external_host', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('test_environment', models.CharField(choices=[('dev', 'Development/Test'), ('prod', 'Production')], default='dev', max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('cloud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffics', to='cloud.Cloud')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'traffics',
            },
        ),
        migrations.CreateModel(
            name='TrafficTestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_run_duration', models.IntegerField(default=1)),
                ('started_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('inprogress', 'In Progress'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('error', 'Error')], default='queued', max_length=20)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('traffic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Traffic')),
            ],
            options={
                'db_table': 'traffic_test_run',
            },
        ),
        migrations.CreateModel(
            name='UDPTestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_tenant', models.CharField(max_length=500)),
                ('dest_tenant', models.CharField(max_length=500)),
                ('src_ep', models.TextField()),
                ('dest_ep', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('jitter', models.CharField(max_length=20)),
                ('bandwidth', models.CharField(max_length=20)),
                ('bandwidth_loss_percent', models.CharField(max_length=20)),
                ('interval_time', models.CharField(max_length=20)),
                ('transferred', models.CharField(max_length=20)),
                ('loss_datagram', models.IntegerField()),
                ('total_datagram', models.IntegerField()),
                ('traffic_test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.TrafficTestRun')),
            ],
            options={
                'db_table': 'udp_test_results',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='traffic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='cloud.Traffic'),
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='traffic_test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.TrafficTestRun'),
        ),
        migrations.AddField(
            model_name='network',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='cloud.Tenant'),
        ),
        migrations.AddField(
            model_name='icmptestresults',
            name='traffic_test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.TrafficTestRun'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Network'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='traffic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Traffic'),
        ),
    ]
