# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icmptestresults',
            name='traffic_test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icmp_test_results', to='cloud.TrafficTestRun'),
        ),
        migrations.AlterField(
            model_name='tcptestresults',
            name='traffic_test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcp_test_results', to='cloud.TrafficTestRun'),
        ),
        migrations.AlterField(
            model_name='udptestresults',
            name='traffic_test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udp_test_results', to='cloud.TrafficTestRun'),
        ),
    ]
