# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20160428_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='report_name',
            field=models.CharField(default='report.csv', max_length=100),
            preserve_default=False,
        ),
    ]
