# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_auto_20160503_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='completed_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 4, 9, 34, 2, 512239, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
