# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_testrun_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='udp_datagram_size',
            field=models.IntegerField(default=1),
        ),
    ]
