# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_traffic_udp_datagram_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udptestresults',
            name='loss_datagram',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='udptestresults',
            name='total_datagram',
            field=models.CharField(max_length=20),
        ),
    ]
