# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_auto_20160504_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udptestresults',
            name='bandwidth_loss_percent',
        ),
        migrations.RemoveField(
            model_name='udptestresults',
            name='interval_time',
        ),
        migrations.RemoveField(
            model_name='udptestresults',
            name='total_datagram',
        ),
        migrations.RemoveField(
            model_name='udptestresults',
            name='transferred',
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='bytes_transferred',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='bytes_transferred_units',
            field=models.CharField(default='bits', max_length=5),
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='cpu_utilization_desc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='cpu_utilization_src',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='datagrams',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='interval_time_end',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='interval_time_start',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='interval_time_units',
            field=models.CharField(default='sec', max_length=5),
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='jitter_units',
            field=models.CharField(default='ms', max_length=5),
        ),
        migrations.AddField(
            model_name='udptestresults',
            name='loss_bandwidth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='udptestresults',
            name='bandwidth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='udptestresults',
            name='jitter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='udptestresults',
            name='loss_datagram',
            field=models.IntegerField(),
        ),
    ]
