# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0011_auto_20160509_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='udptestresults',
            old_name='loss_bandwidth',
            new_name='bandwidth_loss',
        ),
    ]
