# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_auto_20160509_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='udptestresults',
            old_name='loss_datagram',
            new_name='loss_datagrams',
        ),
    ]
