# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0014_auto_20160509_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='udptestresults',
            name='bandwidth_units',
            field=models.CharField(default='bits', max_length=5),
        ),
    ]
