# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0015_udptestresults_bandwidth_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcptestresults',
            old_name='retr',
            new_name='bytes_transferred',
        ),
        migrations.RemoveField(
            model_name='tcptestresults',
            name='interval_time',
        ),
        migrations.RemoveField(
            model_name='tcptestresults',
            name='transferred',
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='bandwidth_units',
            field=models.CharField(default='bits', max_length=5),
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='bytes_transferred_units',
            field=models.CharField(default='bits', max_length=5),
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='cpu_utilization_dest',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='cpu_utilization_src',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='interval_time_end',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='interval_time_start',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='interval_time_units',
            field=models.CharField(default='sec', max_length=5),
        ),
        migrations.AddField(
            model_name='tcptestresults',
            name='retransmits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tcptestresults',
            name='bandwidth',
            field=models.FloatField(),
        ),
    ]
